language: php

php:
  - 7.1
  - 7.2
  - 7.3

addons:
  hosts:
    - awesome.scot

sudo: false


install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - composer install


before_script:
  - export APPLICATION_ENV=travis
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 &
  - "mysql -e 'create database codeception_test;'"
  - nohup php -S awesome.scot:8000 public/index.php &
script:
  - php vendor/bin/codecept run -vvv --coverage-xml --env travis
after_script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml

notifications:
  irc: "irc.freenode.org#bonemvc"
