language: php

services:
  - docker

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

addons:
  hosts:
    - awesome.scot\

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar
  - sudo /etc/init.d/mysql stop
  - docker-compose build
  - docker-compose up -d

before_script:
  - export APPLICATION_ENV=travis
  - docker-compose exec php /usr/bin/composer install

script:
  - docker-compose exec php vendor/bin/codecept run acceptance --env=travis -vvv
  - docker-compose exec php vendor/bin/codecept run  unit --coverage-xml --env=travis -vvv

after_script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml

notifications:
  irc: "irc.freenode.org#bonemvc"
